"""add note color

Revision ID: 435c9127a418
Revises: f9a555bef72a
Create Date: 2026-06-16 13:00:44.359096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435c9127a418'
down_revision: Union[str, Sequence[str], None] = 'f9a555bef72a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('color', sa.String(length=50), server_default='gray', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'color')
    # ### end Alembic commands ###
