"""add_todos_and_user_plan

Revision ID: a43e4d15ea3d
Revises: 5052eed16f72
Create Date: 2026-06-12 21:40:02.068557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43e4d15ea3d'
down_revision: Union[str, Sequence[str], None] = '5052eed16f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('energy_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='energylevel'), nullable=False),
    sa.Column('context', sa.Enum('DESK', 'PHONE', 'ERRANDS', 'QUICK', 'ANY', name='context'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'SNOOZED', 'ARCHIVED', 'PARKING_LOT', name='todostatus'), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('done_for_day', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
    op.create_index(op.f('ix_todos_user_id'), 'todos', ['user_id'], unique=False)
    userplan = sa.Enum('FREE', 'MID', 'MAX', name='userplan')
    userplan.create(op.get_bind())
    op.add_column('users', sa.Column('user_plan', userplan, server_default='FREE', nullable=False))
    op.add_column('users', sa.Column('ai_requests_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('ai_requests_reset_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_requests_reset_at')
    op.drop_column('users', 'ai_requests_used')
    op.drop_column('users', 'user_plan')
    userplan = sa.Enum('FREE', 'MID', 'MAX', name='userplan')
    userplan.drop(op.get_bind())
    op.drop_index(op.f('ix_todos_user_id'), table_name='todos')
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###
