"""add water_intakes table

Revision ID: fb11212f2f87
Revises: a43e4d15ea3d
Create Date: 2026-06-16 12:20:17.163735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb11212f2f87'
down_revision: Union[str, Sequence[str], None] = 'a43e4d15ea3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_intakes_id'), 'water_intakes', ['id'], unique=False)
    op.create_index(op.f('ix_water_intakes_user_id'), 'water_intakes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_intakes_user_id'), table_name='water_intakes')
    op.drop_index(op.f('ix_water_intakes_id'), table_name='water_intakes')
    op.drop_table('water_intakes')
    # ### end Alembic commands ###
